# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1

jobs:
  jvm:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:lein-2.8.1
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install native dev tools
          command: |
            sudo apt-get update
            sudo apt-get -y install gcc zlib1g-dev make lsb-release file
      - run:
          name: Install Clojure
          command: |
            wget -nc https://download.clojure.org/install/linux-install-1.10.1.447.sh
            chmod +x linux-install-1.10.1.447.sh
            sudo ./linux-install-1.10.1.447.sh
      - run:
          name: Run JVM tests
          command: |
            sudo apt-get -y install openssh-server
            sudo grep -v ^# /etc/ssh/sshd_config|grep -v ^$
            sudo mkdir /run/sshd
            make clean lib
            make circle-ci
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run:
          name: Create uberjar and native image
          command: |
            mkdir -p /tmp/release
            make jar
            # lein do clean, uberjar
            # VERSION=$(cat .meta/VERSION)
            # cp target/uberjar/bootleg-$VERSION-standalone.jar /tmp/release

      - store_artifacts:
          path: /tmp/release
          destination: release

  linux:
    docker:
      - image: circleci/clojure:lein-2.8.1
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      GRAALVM_HOME: /home/circleci/graalvm-ce-java8-19.3.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - linux-{{ checksum "project.clj" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Install Clojure
          command: |
            wget https://download.clojure.org/install/linux-install-1.10.1.447.sh
            chmod +x linux-install-1.10.1.447.sh
            sudo ./linux-install-1.10.1.447.sh
      - run:
          name: Install native dev tools
          command: |
            sudo apt-get update
            sudo apt-get -y install gcc zlib1g-dev make
      - run:
          name: Download GraalVM
          command: |
            cd ~
            if ! [ -d graalvm-ce-java8-19.3.1 ]; then
              curl -O -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.1/graalvm-ce-java8-linux-amd64-19.3.1.tar.gz
              tar xzf graalvm-ce-java8-linux-amd64-19.3.1.tar.gz
            fi
            graalvm-ce-java8-19.3.1/bin/gu install native-image
      - run:
          name: Build binary
          command: |
            make copy-libs-to-resource clean all package-linux GRAALVM=$GRAALVM_HOME
          no_output_timeout: 40m
      - run:
          name: Copy artifacts
          command: |
            cp *.tgz /tmp/release
      - save_cache:
          paths:
            - ~/.m2
            - ~/graalvm-ce-java8-19.3.1
          key: linux-{{ checksum "project.clj" }}-{{ checksum ".circleci/config.yml" }}
      - store_artifacts:
          path: /tmp/release
          destination: release
  mac:
    macos:
      xcode: "9.0"
    environment:
      GRAALVM_HOME: /Users/distiller/graalvm-ce-java8-19.3.1/Contents/Home
    steps:
      - checkout
      - restore_cache:
          keys:
            - mac-{{ checksum "project.clj" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Install Clojure
          command: |
            .circleci/script/install-clojure /usr/local
      - run:
          name: Install Leiningen
          command: |
            .circleci/script/install-leiningen
      - run:
          name: Download GraalVM
          command: |
            cd ~
            ls -la
            if ! [ -d graalvm-ce-java8-19.3.1 ]; then
              curl -O -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.1/graalvm-ce-java8-darwin-amd64-19.3.1.tar.gz
              tar xzf graalvm-ce-java8-darwin-amd64-19.3.1.tar.gz
            fi
            $GRAALVM_HOME/bin/gu install native-image
          no_output_timeout: 30m
      - run:
          name: Run MacOS tests
          command: |
            make clean lib JAVA_HOME=$GRAALVM_HOME
            ls -alF

            make jar
            java -Djava.library.path="." -jar target/uberjar/spire-0.1.0-SNAPSHOT-standalone.jar -h

            sudo grep -v ^# /etc/ssh/sshd_config|grep -v ^$
            #sudo mkdir /run/sshd

            make circle-ci
            make clean
      - run:
          name: Build binary
          command: |
            #make clean
            make all macos-package GRAALVM=$GRAALVM_HOME
          no_output_timeout: 60m
      - run:
          name: Test running binary
          command: |
            ./spire -h
          no_output_timeout: 1m
      - run:
          name: Client tests
          command: |
            make macos-client-test-jvm
          no_output_timeout: 1m
      - run:
          name: Client tests
          command: |
            make macos-client-test
          no_output_timeout: 1m

      - run:
          name: Dump .spire directory
          command: |
            ls -alFR ~/.spire
          no_output_timeout: 1m

      - save_cache:
          paths:
            - ~/.m2
            - ~/graalvm-ce-java8-19.3.1
          key: mac-{{ checksum "project.clj" }}-{{ checksum ".circleci/config.yml" }}
      - store_artifacts:
          path: build
          destination: build

workflows:
  version: 2
  ci:
    jobs:
      - jvm:
          filters:
            branches:
              only: master
      - mac:
          filters:
            branches:
              only: master

      # build on free circleci account runs out of ram
      # Error: Image build request failed with exit status 137
      # - linux
